   - name: Get status of directory
      stat:
        path: "{{ dirname }}"
      register: dir_name

    - name: Create the directory unless it already exists
      file:
        path: "{{ dirname }}"
        state: directory
      delegate_to: localhost
      when: "not dir_name.stat.exists"